# Generated by Django 3.2.15 on 2022-08-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('created_at',)},
        ),
    ]
